name = "hehospitality"
main = "src/index.js"
compatibility_date = "2026-01-01"

account_id = "54ffc241388f24fd372db84d6d6e6455"
workers_dev = false

# Route binding is optional here; you can set the route in the Cloudflare dashboard.
# Example route: logos.hehospitalityconsulting.com/*
# See "Bind route" section below.

[[r2_buckets]]
binding = "picture"
bucket_name = "branding"
preview = false


